In [41]:
import time
import numpy as np


In [42]:
conv_1_1_w=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\conv1_1_kernel_0.npy').transpose(3,2,0,1)
conv_1_1_b=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\conv1_1_bias_0.npy')
conv_1_2_w=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\conv1_2_kernel_0.npy').transpose(3,2,0,1)
conv_1_2_b=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\conv1_2_bias_0.npy')
conv_2_1_w=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\conv2_1_kernel_0.npy').transpose(3,2,0,1)
conv_2_1_b=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\conv2_1_bias_0.npy')
conv_2_2_w=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\conv2_2_kernel_0.npy').transpose(3,2,0,1)
conv_2_2_b=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\conv2_2_bias_0.npy')
conv_3_1_w=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\conv3_1_kernel_0.npy').transpose(3,2,0,1)
conv_3_1_b=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\conv3_1_bias_0.npy')
conv_3_2_w=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\conv3_2_kernel_0.npy').transpose(3,2,0,1)
conv_3_2_b=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\conv3_2_bias_0.npy')
conv_3_3_w=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\conv3_3_kernel_0.npy').transpose(3,2,0,1)
conv_3_3_b=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\conv3_3_bias_0.npy')
conv_4_1_w=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\conv4_1_kernel_0.npy').transpose(3,2,0,1)
conv_4_1_b=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\conv4_1_bias_0.npy')
atrou_conv_4_2_w=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\atrousconv4_2_kernel_0.npy').transpose(3,2,0,1)
atrou_conv_4_2_b=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\atrousconv4_2_bias_0.npy')
atrou_conv_4_3_w=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\atrousconv4_3_kernel_0.npy').transpose(3,2,0,1)
atrou_conv_4_3_b=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\atrousconv4_3_bias_0.npy')
########################
conv_seg_1_1_w=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\convseg_1_1_kernel_0.npy').transpose(3,2,0,1)
conv_seg_1_1_b=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\convseg_1_1_bias_0.npy')
conv_seg_2_1_w=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\convseg_2_1_kernel_0.npy').transpose(3,2,0,1)
conv_seg_2_1_b=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\convseg_2_1_bias_0.npy')
conv_seg_3_1_w=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\convseg_3_1_kernel_0.npy').transpose(3,2,0,1)
conv_seg_3_1_b=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\convseg_3_1_bias_0.npy')

seg_1_2_w=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\seg_1_2_kernel_0.npy').transpose(3,2,0,1)
seg_1_2_b=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\seg_1_2_bias_0.npy')
seg_2_2_w=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\seg_2_2_kernel_0.npy').transpose(3,2,0,1)
seg_2_2_b=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\seg_2_2_bias_0.npy')
seg_3_2_w=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\seg_3_2_kernel_0.npy').transpose(3,2,0,1)
seg_3_2_b=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\seg_3_2_bias_0.npy')
##########################
ori_1_2_w=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\ori_1_2_kernel_0.npy').transpose(3,2,0,1)
ori_1_2_b=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\ori_1_2_bias_0.npy')
ori_2_2_w=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\ori_2_2_kernel_0.npy').transpose(3,2,0,1)
ori_2_2_b=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\ori_2_2_bias_0.npy')
ori_3_2_w=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\ori_3_2_kernel_0.npy').transpose(3,2,0,1)
ori_3_2_b=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\ori_3_2_bias_0.npy')


conv_ori_1_1_w=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\convori_1_1_kernel_0.npy').transpose(3,2,0,1)
conv_ori_1_1_b=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\convori_1_1_bias_0.npy')
conv_ori_2_1_w=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\convori_2_1_kernel_0.npy').transpose(3,2,0,1)
conv_ori_2_1_b=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\convori_2_1_bias_0.npy')
conv_ori_3_1_w=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\convori_3_1_kernel_0.npy').transpose(3,2,0,1)
conv_ori_3_1_b=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\convori_3_1_bias_0.npy')


##########################
bn_1_1_beta=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-1_1_beta_0.npy')
bn_1_1_gamma=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-1_1_gamma_0.npy')
bn_1_1_moving_mean=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-1_1_moving_mean_0.npy')
bn_1_1_moving_variance=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-1_1_moving_variance_0.npy')

bn_1_2_beta=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-1_2_beta_0.npy')
bn_1_2_gamma=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-1_2_gamma_0.npy')
bn_1_2_moving_mean=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-1_2_moving_mean_0.npy')
bn_1_2_moving_variance=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-1_2_moving_variance_0.npy')

bn_2_1_beta=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-2_1_beta_0.npy')
bn_2_1_gamma=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-2_1_gamma_0.npy')
bn_2_1_moving_mean=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-2_1_moving_mean_0.npy')
bn_2_1_moving_variance=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-2_1_moving_variance_0.npy')

bn_2_2_beta=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-2_2_beta_0.npy')
bn_2_2_gamma=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-2_2_gamma_0.npy')
bn_2_2_moving_mean=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-2_2_moving_mean_0.npy')
bn_2_2_moving_variance=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-2_2_moving_variance_0.npy')

bn_3_1_beta=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-3_1_beta_0.npy')
bn_3_1_gamma=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-3_1_gamma_0.npy')
bn_3_1_moving_mean=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-3_1_moving_mean_0.npy')
bn_3_1_moving_variance=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-3_1_moving_variance_0.npy')

bn_3_2_beta=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-3_2_beta_0.npy')
bn_3_2_gamma=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-3_2_gamma_0.npy')
bn_3_2_moving_mean=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-3_2_moving_mean_0.npy')
bn_3_2_moving_variance=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-3_2_moving_variance_0.npy')

bn_3_3_beta=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-3_3_beta_0.npy')
bn_3_3_gamma=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-3_3_gamma_0.npy')
bn_3_3_moving_mean=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-3_3_moving_mean_0.npy')
bn_3_3_moving_variance=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-3_3_moving_variance_0.npy')

bn_4_1_beta=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-4_1_beta_0.npy')
bn_4_1_gamma=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-4_1_gamma_0.npy')
bn_4_1_moving_mean=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-4_1_moving_mean_0.npy')
bn_4_1_moving_variance=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-4_1_moving_variance_0.npy')

bn_4_2_beta=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-4_2_beta_0.npy')
bn_4_2_gamma=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-4_2_gamma_0.npy')
bn_4_2_moving_mean=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-4_2_moving_mean_0.npy')
bn_4_2_moving_variance=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-4_2_moving_variance_0.npy')

bn_4_3_beta=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-4_3_beta_0.npy')
bn_4_3_gamma=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-4_3_gamma_0.npy')
bn_4_3_moving_mean=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-4_3_moving_mean_0.npy')
bn_4_3_moving_variance=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-4_3_moving_variance_0.npy')
##########################
bn_ori_1_1_beta=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-ori_1_1_beta_0.npy')
bn_ori_1_1_gamma=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-ori_1_1_gamma_0.npy')
bn_ori_1_1_moving_mean=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-ori_1_1_moving_mean_0.npy')
bn_ori_1_1_moving_variance=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-ori_1_1_moving_variance_0.npy')

bn_ori_2_1_beta=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-ori_2_1_beta_0.npy')
bn_ori_2_1_gamma=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-ori_2_1_gamma_0.npy')
bn_ori_2_1_moving_mean=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-ori_2_1_moving_mean_0.npy')
bn_ori_2_1_moving_variance=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-ori_2_1_moving_variance_0.npy')

bn_ori_3_1_beta=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-ori_3_1_beta_0.npy')
bn_ori_3_1_gamma=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-ori_3_1_gamma_0.npy')
bn_ori_3_1_moving_mean=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-ori_3_1_moving_mean_0.npy')
bn_ori_3_1_moving_variance=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-ori_3_1_moving_variance_0.npy')
##########################
bn_seg_1_1_beta=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-seg_1_1_beta_0.npy')
bn_seg_1_1_gamma=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-seg_1_1_gamma_0.npy')
bn_seg_1_1_moving_mean=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-seg_1_1_moving_mean_0.npy')
bn_seg_1_1_moving_variance=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-seg_1_1_moving_variance_0.npy')

bn_seg_2_1_beta=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-seg_2_1_beta_0.npy')
bn_seg_2_1_gamma=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-seg_2_1_gamma_0.npy')
bn_seg_2_1_moving_mean=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-seg_2_1_moving_mean_0.npy')
bn_seg_2_1_moving_variance=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-seg_2_1_moving_variance_0.npy')

bn_seg_3_1_beta=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-seg_3_1_beta_0.npy')
bn_seg_3_1_gamma=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-seg_3_1_gamma_0.npy')
bn_seg_3_1_moving_mean=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-seg_3_1_moving_mean_0.npy')
bn_seg_3_1_moving_variance=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\bn-seg_3_1_moving_variance_0.npy')
#####################
prelu_1_1_alpha=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\prelu-1_1_alpha_0.npy')
prelu_1_2_alpha=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\prelu-1_2_alpha_0.npy')
prelu_2_1_alpha=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\prelu-2_1_alpha_0.npy')
prelu_2_2_alpha=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\prelu-2_2_alpha_0.npy')
prelu_3_1_alpha=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\prelu-3_1_alpha_0.npy')
prelu_3_2_alpha=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\prelu-3_2_alpha_0.npy')
prelu_3_3_alpha=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\prelu-3_3_alpha_0.npy')
prelu_4_1_alpha=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\prelu-4_1_alpha_0.npy')
prelu_4_2_alpha=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\prelu-4_2_alpha_0.npy')
prelu_4_3_alpha=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\prelu-4_3_alpha_0.npy')
##############################
prelu_ori_1_1_alpha=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\prelu-ori_1_1_alpha_0.npy')
prelu_ori_2_1_alpha=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\prelu-ori_2_1_alpha_0.npy')
prelu_ori_3_1_alpha=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\prelu-ori_3_1_alpha_0.npy')
############################
prelu_seg_1_1_alpha=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\prelu-seg_1_1_alpha_0.npy')
prelu_seg_2_1_alpha=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\prelu-seg_2_1_alpha_0.npy')
prelu_seg_3_1_alpha=np.load('F:\\codespace\\jupyter\\CNNIOT-master\\CNNIOT-master\\weights\\prelu-seg_3_1_alpha_0.npy')


In [45]:
# print(bn_1_1_beta)
# print(bn_1_1_gamma.shape)
# print(bn_1_1_moving_mean.shape)
# print(bn_1_1_moving_variance.shape)
# print(np.append(np.append(np.append(bn_1_1_gamma,bn_1_1_beta),bn_1_1_moving_mean),bn_1_1_moving_variance))
#python 读取bmp文件转换为numpy格式
###########ndarray=np.pad(array,(1,2),'constant', constant_values=(0,2)) 
data=np.array([[[1,2],[2,3]],[[1,2],[2,3]]])   #example
data1=np.pad(data,((0,0),(1,1),(1,1)),'constant',constant_values=0)
data.shape[1]
print(data1)
print(conv_1_1_w.shape)
print(conv_1_1_b.shape)

print(ori_1_2_w.shape)


[[[0 0 0 0]
  [0 1 2 0]
  [0 2 3 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 1 2 0]
  [0 2 3 0]
  [0 0 0 0]]]
(64, 1, 3, 3)
(64,)
(90, 128, 1, 1)


In [ ]:
#卷积
#输入通道，输出通道，卷积高，卷积宽，步长高，步长宽，padding，relu，weight，bias，dila_rate,precision
#池化
#Win_H, Win_W, Stride_H, Stride_W, Pool_type, Padding, Relu, Precision=10000
#bn
#Input_Size,Weigth,relu,Precision

#feature extration VGG
conv_1_1_conv = CNNIOT.Convolution2D(1,64,3,3,1,1,0,0,conv_1_1_w,conv_1_1_b,1,10000)

conv_1_1_bn = CNNTOT.Batch_Norm(64,np.append(np.append(np.append(np.append(bn_1_1_gamma,bn_1_1_beta),bn_1_1_moving_mean),bn_1_1_moving_variance),prelu_1_1_alpha),1,10000)
conv_1_2_conv = CNNIOT.Convolution2D(64,64,3,3,1,1,0,0,conv_1_2_w,conv_1_2_b,1,10000)
conv_1_2_bn = CNNTOT.Batch_Norm(64,np.append(np.append(np.append(np.append(bn_1_2_gamma,bn_1_2_beta),bn_1_2_moving_mean),bn_1_2_moving_variance),prelu_1_2_alpha),1,10000)
Maxpooling_1=CNNIOT.Pool(2,2,2,2,'Max',0,0,10000)

conv_2_1_conv = CNNIOT.Convolution2D(64,128,3,3,1,1,0,0,conv_2_1_w,conv_2_1_b,1,10000)
conv_2_1_bn = CNNTOT.Batch_Norm(128,np.append(np.append(np.append(np.append(bn_2_1_gamma,bn_2_1_beta),bn_2_1_moving_mean),bn_2_1_moving_variance),prelu_2_1_alpha),1,10000)
conv_2_2_conv = CNNIOT.Convolution2D(128,128,3,3,1,1,0,0,conv_2_2_w,conv_2_2_b,1,10000)
conv_2_2_bn = CNNTOT.Batch_Norm(128,np.append(np.append(np.append(np.append(bn_2_2_gamma,bn_2_2_beta),bn_2_2_moving_mean),bn_2_2_moving_variance),prelu_2_2_alpha),1,10000)
Maxpooling_2=CNNIOT.Pool(2,2,2,2,'Max',0,0,10000)

conv_3_1_conv = CNNIOT.Convolution2D(128,256,3,3,1,1,0,0,conv_3_1_w,conv_3_1_b,1,10000)
conv_3_1_bn = CNNTOT.Batch_Norm(256,np.append(np.append(np.append(np.append(bn_3_1_gamma,bn_3_1_beta),bn_3_1_moving_mean),bn_3_1_moving_variance),prelu_3_1_alpha),1,10000)
conv_3_2_conv = CNNIOT.Convolution2D(256,256,3,3,1,1,0,0,conv_3_2_w,conv_3_2_b,1,10000)
conv_3_2_bn = CNNTOT.Batch_Norm(256,np.append(np.append(np.append(np.append(bn_3_2_gamma,bn_3_2_beta),bn_3_2_moving_mean),bn_3_2_moving_variance),prelu_3_2_alpha),1,10000)
conv_3_3_conv = CNNIOT.Convolution2D(256,256,3,3,1,1,0,0,conv_3_3_w,conv_3_3_b,1,10000)
conv_3_3_bn = CNNTOT.Batch_Norm(256,np.append(np.append(np.append(np.append(bn_3_3_gamma,bn_3_3_beta),bn_3_3_moving_mean),bn_3_3_moving_variance),prelu_3_3_alpha),1,10000)
Maxpooling_3=CNNIOT.Pool(2,2,2,2,'Max',0,0,10000)

#multi_scale aspp
conv_4_1_conv=CNNIOT.Convolution2D(256,256,3,3,1,1,0,0,conv_4_1_w,conv_4_1_b,1,10000)
conv_4_1_bn=CNNTOT.Batch_Norm(256,np.append(np.append(np.append(np.append(bn_4_1_gamma,bn_4_1_beta),bn_4_1_moving_mean),bn_4_1_moving_variance),prelu_4_1_alpha),1,10000)
conv_ori_1_1_conv=CNNIOT.Convolution2D(256,128,1,1,1,1,0,0,conv_ori_1_1_w,conv_ori_1_1_b,1,10000)
conv_ori_1_1_bn=CNNTOT.Batch_Norm(128,np.append(np.append(np.append(np.append(bn_ori_1_1_gamma,bn_ori_1_1_beta),bn_ori_1_1_moving_mean),bn_ori_4_2_moving_variance),prelu_ori_1_1_alpha),1,10000)
conv_1_2_conv=CNNIOT.Convolution2D(128,90,1,1,1,1,0,0,ori_1_2_w,ori_1_2_b,1,10000)
conv_seg_1_1_conv=CNNIOT.Convolution2D(256,128,1,1,1,1,0,0,conv_seg_1_1_w,conv_seg_1_1_b,1,10000)
conv_seg_1_1_bn=CNNTOT.Batch_Norm(128,np.append(np.append(np.append(np.append(bn_seg_1_1_gamma,bn_seg_1_1_beta),bn_seg_1_1_moving_mean),bn_seg_4_3_moving_variance),prelu_seg_1_1_alpha),1,10000)
conv_seg_1_2_conv=CNNIOT.Convolution2D(128,1,1,1,1,1,0,0,seg_1_2_w,seg_1_2_b,1,10000)

conv_4_2_conv=CNNIOT.Convolution2D(256,256,3,3,1,1,0,0,atrou_conv_4_2_w,atrou_conv_4_2_b,4,10000)
conv_4_2_bn=CNNTOT.Batch_Norm(256,np.append(np.append(np.append(np.append(bn_4_2_gamma,bn_4_2_beta),bn_4_2_moving_mean),bn_4_2_moving_variance),prelu_4_2_alpha),1,10000)
conv_ori_2_1_conv=CNNIOT.Convolution2D(256,128,1,1,1,1,0,0,conv_ori_2_1_w,conv_ori_2_1_b,1,10000)
conv_ori_2_1_bn=CNNTOT.Batch_Norm(128,np.append(np.append(np.append(np.append(bn_ori_2_1_gamma,bn_ori_2_1_beta),bn_ori_2_1_moving_mean),bn_ori_2_1_moving_variance),prelu_ori_2_1_alpha),1,10000)
conv_2_2_conv=CNNIOT.Convolution2D(128,90,1,1,1,1,0,0,ori_2_2_w,ori_2_2_b,1,10000)
conv_seg_2_1_conv=CNNIOT.Convolution2D(256,128,1,1,1,1,0,0,conv_seg_2_1_w,conv_seg_2_1_b,1,10000)
conv_seg_2_1_bn=CNNTOT.Batch_Norm(128,np.append(np.append(np.append(np.append(bn_seg_2_1_gamma,bn_seg_2_1_beta),bn_seg_2_1_moving_mean),bn_seg_2_1_moving_variance),prelu_seg_2_1_alpha),1,10000)
conv_seg_2_2_conv=CNNIOT.Convolution2D(128,1,1,1,1,1,0,0,seg_2_2_w,seg_2_2_b,1,10000)

conv_4_3_conv=CNNIOT.Convolution2D(256,256,3,3,1,1,0,0,atrou_conv_4_3_w,atrou_conv_4_3_b,8,10000)
conv_4_3_bn=CNNTOT.Batch_Norm(256,np.append(np.append(np.append(np.append(bn_4_3_gamma,bn_4_3_beta),bn_4_3_moving_mean),bn_4_3_moving_variance),prelu_4_3_alpha),1,10000)
conv_ori_3_1_conv=CNNIOT.Convolution2D(256,128,1,1,1,1,0,0,conv_ori_3_1_w,conv_ori_3_1_b,1,10000)
conv_ori_3_1_bn=CNNTOT.Batch_Norm(128,np.append(np.append(np.append(np.append(bn_ori_3_1_gamma,bn_ori_3_1_beta),bn_ori_3_1_moving_mean),bn_ori_3_1_moving_variance),prelu_ori_3_1_alpha),1,10000)
conv_3_2_conv=CNNIOT.Convolution2D(128,90,1,1,1,1,0,0,ori_3_2_w,ori_3_2_b,1,10000)
conv_seg_3_1_conv=CNNIOT.Convolution2D(256,128,1,1,1,1,0,0,conv_seg_3_1_w,conv_seg_3_1_b,1,10000)
conv_seg_3_1_bn=CNNTOT.Batch_Norm(128,np.append(np.append(np.append(np.append(bn_seg_3_1_gamma,bn_seg_3_1_beta),bn_seg_3_1_moving_mean),bn_seg_3_1_moving_variance),prelu_seg_3_1_alpha),1,10000)
conv_seg_3_2_conv=CNNIOT.Convolution2D(128,1,1,1,1,1,0,0,seg_3_2_w,seg_3_2_b,1,10000)


In [ ]:
#ndarray=np.pad(array,(1,2),'constant', constant_values=(0,2)) 
def test(testnumber):
    total = 0
    data2 = data[0:testnumber]
    size = data2.shape
    for i0 in range(0, size[0]):
        
        #feature extraction vgg
        x=np.pad(data2[i0],((0,0),(1,1),(1,1)),'constant',constant_values=0)
        x=conv_1_1_conv.forward(x,CNNIOT.dma)
        x=conv_1_1_bn.forward(x,CNNIOT.dma)
        x=np.pad(x,((0,0),(1,1),(1,1)),'constant',constant_values=0)
        x= conv_1_2_conv.forward(x,CNNIOT.dma)
        x=conv_1_2_bn.forward(x,CNNIOT.dma)
        x= Maxpooling_1.forward(x,CNNIOT.dma)
        
        x=np.pad(x,((0,0),(1,1),(1,1)),'constant',constant_values=0)
        x=conv_2_1_conv.forward(x,CNNIOT.dma)
        x=conv_2_1_bn.forward(x,CNNIOT.dma)
        x=np.pad(x,((0,0),(1,1),(1,1)),'constant',constant_values=0)
        x=conv_2_2_conv.forward(x,CNNIOT.dma)
        x=conv_2_2_bn.forward(x,CNNIOT.dma)
        x=Maxpooling_2.forward(x,CNNIOT.dma)
        
        x=np.pad(x,((0,0),(1,1),(1,1)),'constant',constant_values=0)
        x=conv_3_1_conv.forward(x,CNNIOT.dma)
        x=conv_3_1_bn.forward(x,CNNIOT.dma)
        x=np.pad(x,((0,0),(1,1),(1,1)),'constant',constant_values=0)
        x=conv_3_2_conv.forward(x,CNNIOT.dma)
        x=conv_3_2_bn.forward(x,CNNIOT.dma)
        x=np.pad(x,((0,0),(1,1),(1,1)),'constant',constant_values=0)
        x=conv_3_3_conv.forward(x,CNNIOT.dma)
        x=conv_3_3_bn.forward(x,CNNIOT.dma)
        x=Maxpooling_3.forward(x,CNNIOT.dma)
        
        #multi_scale aspp
        x=np.pad(x,((0,0),(1,1),(1,1)),'constant',constant_values=0)
        scale_1=conv_4_1_conv.forward(x,CNNIOT.dma)
        scale_1=conv_4_1_bn.forward(scale_1,CNNIOT.dma)
        x=np.pad(x,((0,0),(1,1),(1,1)),'constant',constant_values=0)
        ori_1=conv_ori_1_1_conv.forward(scale_1,CNNIOT.dma)
        ori_1=conv_ori_1_1_bn.forward(ori_1,CNNIOT.dma)
        x=np.pad(x,((0,0),(1,1),(1,1)),'constant',constant_values=0)
        ori_1=conv_1_2_conv.forward(ori_1,CNNIOT.dma)
        x=np.pad(x,((0,0),(1,1),(1,1)),'constant',constant_values=0)
        seg_1=conv_seg_1_1_conv.forward(scale_1,CNNIOT.dma)
        seg_1=conv_seg_1_1_bn.forward(seg_1,CNNIOT.dma)
        x=np.pad(x,((0,0),(1,1),(1,1)),'constant',constant_values=0)
        seg_1=conv_seg_1_2_conv.forward(seg_1,CNNIOT.dma)

        x=np.pad(x,((0,0),(4,4),(4,4)),'constant',constant_values=0)
        scale_2=conv_4_2_conv.forward(x,CNNIOT.dma)
        scale_2=conv_4_2_bn.forward(scale_2,CNNIOT.dma)
        x=np.pad(x,((0,0),(1,1),(1,1)),'constant',constant_values=0)
        ori_2=conv_ori_2_1_conv.forward(scale_2,CNNIOT.dma)
        ori_2=conv_ori_2_1_bn.forward(ori_2,CNNIOT.dma)
        x=np.pad(x,((0,0),(1,1),(1,1)),'constant',constant_values=0)
        ori_2=conv_2_2_conv.forward(ori_2,CNNIOT.dma)
        x=np.pad(x,((0,0),(1,1),(1,1)),'constant',constant_values=0)
        seg_2=conv_seg_2_1_conv.forward(scale_2,CNNIOT.dma)
        seg_2=conv_seg_2_1_bn.forward(seg_2,CNNIOT.dma)
        x=np.pad(x,((0,0),(1,1),(1,1)),'constant',constant_values=0)
        seg_2=conv_seg_2_2_conv.forward(seg_2,CNNIOT.dma)

        x=np.pad(x,((0,0),(8,8),(8,8)),'constant',constant_values=0)
        scale_3=conv_4_3_conv.forward(x,CNNIOT.dma)
        scale_3=conv_4_3_bn.forward(scale_3,CNNIOT.dma)
        x=np.pad(x,((0,0),(1,1),(1,1)),'constant',constant_values=0)
        ori_3=conv_ori_3_1_conv.forward(scale_3,CNNIOT.dma)
        ori_3=conv_ori_3_1_bn.forward(ori_3,CNNIOT.dma)
        x=np.pad(x,((0,0),(1,1),(1,1)),'constant',constant_values=0)
        ori_3=conv_3_2_conv.forward(ori_3,CNNIOT.dma)
        x=np.pad(x,((0,0),(1,1),(1,1)),'constant',constant_values=0)
        seg_3=conv_seg_3_1_conv.forward(scale_3,CNNIOT.dma)
        seg_3=conv_seg_3_1_bn.forward(seg_3,CNNIOT.dma)
        x=np.pad(x,((0,0),(1,1),(1,1)),'constant',constant_values=0)
        seg_3=conv_seg_3_2_conv.forward(seg_3,CNNIOT.dma)
    